[package]
name = "fast_zsh"
version = "0.2.0"
authors = ["Aaron Hill <aa1ronham@gmail.com>"]

[dependencies]
lazy_static = "1.2.0"

[build-dependencies]
bindgen = "0.54.0"


[lib]
name = "fastbrackets"
crate-type = ["dylib"]


[profile.release]
debug = true

[profile.bench]
debug = true
